import type { QuestionDifficulty } from '@/types';

export const PREDEFINED_QUESTIONS: Record<QuestionDifficulty, string[]> = {
  'family-friendly': [
    'be the best looking in the room?',
    'be the smartest in the group?',
    'win a hot dog eating contest?',
    'trip over air?',
    'adopt a dozen cats?',
    'tell the corniest jokes?',
    'become a famous influencer?',
    'survive a zombie apocalypse?',
    'have the best singing voice?',
    'be the most likely to forget a birthday?',
    'laugh at the wrong moment?',
    'organize a surprise party?',
    'binge-watch an entire series in one day?',
    'be the most competitive during board games?',
    'have the messiest room?',
  ],
  'getting-personal': [
    'have a secret admirer?',
    'be the biggest drama queen/king?',
    'cry during a sad movie?',
    'have had a crush on a friend\'s sibling?',
    'be the most likely to stalk an ex on social media?',
    'have the most embarrassing childhood nickname?',
    'be the first to get married?',
    'have a secret talent?',
    'be the most likely to lie to get out of trouble?',
    'have read someone else\'s diary?',
    'be the pickiest eater?',
    'be the most likely to get a tattoo they regret?',
    'be the worst at keeping a secret?',
    'be the first to have children?',
    'have the weirdest fear?',
  ],
  'hot-seat-exclusive': [
    'have lost their v-card first?',
    'have the highest body count?',
    'be the poorest financially right now?',
    'have a one-night stand on vacation?',
    'have the weirdest internet search history?',
    'have a fake ID?',
    'get arrested for something silly?',
    'have slept with the most people?',
    'be the most likely to ghost someone?',
    'have a secret OnlyFans account?',
    'have hooked up with someone in this room?',
    'be the most likely to get into a physical fight?',
    'be the kinkiest?',
    'have sent nudes?',
    'be the most likely to cheat on a partner?',
  ],
};
